name: Update branch

on:
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: "full"

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          ./
          pulumi_wasm_generator/tests/output/command_provider/
          pulumi_wasm_generator/tests/output/docker_provider/
          pulumi_wasm_generator/tests/output/random_provider/
          cargo-pulumi/tests/fixtures/example -> targets/target/run_from_main_directory
          cargo-pulumi/tests/fixtures/example -> targets/target/run_from_subdirectory
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.22.0'
        cache-dependency-path: "**/go.sum"
    - run: go version
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "25.3"
        repo-token: ${{ github.token }}
    - run: protoc --version
    - run: brew install pulumi
      if: runner.os == 'macOS'
    - run: pulumi version
    - run: pulumi login --local
    - uses: extractions/setup-just@v2
    - uses: cargo-bins/cargo-binstall@main
    - name: Install requirements
      run: just install-requirements
    - name: Build
      run: just build
    - name: Test
      run: just test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUST_BACKTRACE: "full"
    - name: Commit report
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -am "Update branch"
        git push
